name: Build and deploy Python app to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Use the Python version your app requires

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          source venv/bin/activate
          pytest  # Replace with your test command

      - name: Zip application for deployment
        run: |
          zip -r application.zip . -x '*.git*' '*.github*' 'venv/*'

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: application.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-aws.outputs.aws-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: application
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Elastic Beanstalk
        id: deploy-to-aws
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "studentsperformance" \
            --version-label "$GITHUB_SHA" \
            --source-bundle S3Bucket="your-s3-bucket-name",S3Key="application.zip" \
            --region ${{ secrets.AWS_REGION }}

          aws elasticbeanstalk update-environment \
            --environment-name "studentsperformance-env" \
            --version-label "$GITHUB_SHA" \
            --region ${{ secrets.AWS_REGION }}